name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Deploy to GitHub Pages
        run: |
          # Create a gh-pages branch
          git checkout --orphan gh-pages
          
          # Remove all existing files from the gh-pages branch (except the .git folder)
          git rm -rf .

          # Copy all files and directories into 'dist', excluding the 'dist' directory itself
          # You can use `rsync` to avoid copying the 'dist' folder into itself
          rsync -av --exclude='./dist' ./ ./dist/

          # Add everything and commit
          git add .
          git commit -m "Deploy to GitHub Pages"

          # Push the files to the gh-pages branch
          git push origin gh-pages --force
